[build]
  base = "."
  publish = "public/"
  edge_handlers = "src/edge-handlers/"

[dev]
  port = 8889
  autoLaunch = false
  framework = "#static"

[functions]
  directory = "src/functions/"    

[[edge_handlers]]
  path = "/.netlify/functions/graphql"
  handler = "cacheGraphQL"
